throw Error('Miền nghiệp vụ 3.2 có nhiệm vụ bắt buộc và phân quyền văn phòng. Không tái tạo từ Code.gs 3.1; chỉnh domain.js và chạy npm test.');
const fs=require('fs');
const code=fs.readFileSync('kpi-v2/Code.gs','utf8').replace("const KPI_VERSION='2.0.0-2026.10.06';","const KPI_VERSION='3.0.0-supabase';").replace(/\{key:'driveFolderId',value:'[^']*'\}/g,"{key:'driveFolderId',value:''}").replaceAll('config:kpiCfg_()','config:kpiClientCfg_()');
const adapter=`
function kpiClientCfg_(){const c=kpiCfg_();return {period:c.period,schoolRule:c.schoolRule,bonusMode:c.bonusMode};}\nfunction kpiRawRows_(name){return (tables[name]||[]).map(r=>structuredClone(r));}
function kpiWrite_(name,o){if(!headers[name])throw Error('Bảng không hợp lệ');const rows=tables[name]||(tables[name]=[]);const row=o._row||Math.max(1,...rows.map(r=>r._row))+1;const value={_row:row};headers[name].forEach(k=>value[k]=o[k]===undefined?'':typeof o[k]==='object'?JSON.stringify(o[k]):o[k]);const i=rows.findIndex(r=>r._row===row);if(i<0)rows.push(value);else rows[i]=value;writes.set(name+'|'+row,{table_name:name,row_no:row,data:value});if(KPI_READ_CACHE)delete KPI_READ_CACHE[name];KPI_INDEX_CACHE={};if(name==='gvcnv')KPI_PEOPLE_CACHE=null;}
function kpiSheet_(name){return {getLastRow:()=>Math.max(1,...(tables[name]||[]).map(r=>r._row))};}
function kpiLocked_(fn){return fn();}
function kpiAuth_(token){if(!actor||token!==sessionToken)throw Error('Phiên không hợp lệ');const u=kpiPeople_().find(x=>x.email===actor);if(!u)throw Error('Không có tài khoản');return u;}
function kpiFile_(f,u,t){if(!f)return {fileId:'',fileName:''};return prepareFile(f,u,t);}
function kpiSetPerson_(){throw Error('Mật khẩu do dịch vụ xác thực quản lý');}
`;
fs.writeFileSync('kpi-v2/supabase/functions/kpi-api/domain.js',`// Generated from validated Code.gs; request-local state. Do not edit manually.\nimport {createHash,createHmac} from 'node:crypto';\n/** @param {any} options */\nexport function createDomain(options){\nconst {tables,headers,actor='',sessionToken='',cacheValues={},prepareFile=()=>{throw Error('Chưa có bộ lưu minh chứng')}}=options;\nconst writes=new Map(),cacheWrites=new Map(),cache=new Map(Object.entries(cacheValues));\nconst Utilities={getUuid:()=>crypto.randomUUID(),DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(_,s)=>[...createHash('sha256').update(s).digest()],computeHmacSha256Signature:(s,k)=>[...createHmac('sha256',k).update(s).digest()],formatDate:d=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)};\nconst CacheService={getScriptCache:()=>({get:k=>cache.get(k),put:(k,v,ttl)=>{cache.set(k,v);cacheWrites.set(k,{key:k,value:v,ttl});},remove:k=>{cache.delete(k);cacheWrites.set(k,{key:k,remove:true});}})};\n${code}\n${adapter}\nreturn {dispatch:(a,p,t=sessionToken)=>kpiDispatch_(a,p,t),publicData:()=>({version:'3.0.0-supabase',config:kpiClientCfg_(),catalog:kpiRows_('bang_luong_hoa_kpi')}),people:()=>kpiPeople_().map(kpiPublicUser_),writes:()=>[...writes.values()],cacheWrites:()=>[...cacheWrites.values()]};\n}\n`);
