import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {createDomain} from '../supabase/functions/kpi-api/domain.js';import {CURRENT_CATALOG} from '../supabase/functions/kpi-api/catalog.js';
const ctx=vm.createContext({});vm.runInContext(fs.readFileSync('demo/headers.js','utf8')+';globalThis.h=DEMO_HEADERS',ctx);const headers=JSON.parse(JSON.stringify(ctx.h));headers.bang_luong_hoa_kpi.push('mandatory','periodic');headers.kpi_thuong_chuyen_ky=['id','email','sourcePeriod','targetPeriod','examYear','assessmentYear','taskId','category','reference','requested','approved','status','version','at','reviewer','reviewNote'];
const tables=Object.fromEntries(Object.keys(headers).map(n=>[n,[]]));const users=[['a','GVBM GVCN','Ngoại ngữ'],['b','GVBM','Ngoại ngữ'],['leader','GVBM TTCM','Ngoại ngữ'],['deputy','GVBM TPCM','Ngoại ngữ'],['ht','HT','BGH'],['hp','PHT','BGH'],['vpl','TTVP VT','Văn phòng'],['vpd','TPVP KT','Văn phòng'],['vt','VT','Văn phòng'],['kt','KT','Văn phòng'],['math','GVBM','Toán']];tables.gvcnv=users.map(([email,roles,unit],i)=>({_row:i+2,Email:email,'Họ và tên':email,'Vai trò KPI':roles,Tổ:unit}));tables.bang_luong_hoa_kpi=CURRENT_CATALOG.map((c,i)=>({...c,_row:i+2}));tables.kpi_cau_hinh=[{_row:2,key:'period',value:'2026-2027'},{_row:3,key:'bonusMode',value:'school'}];const cache={};
function call(actor,action,p={}){const candidate=structuredClone(tables),d=createDomain({tables:candidate,headers,actor,sessionToken:'s',cacheValues:cache});const r=d.dispatch(action,p,'s');for(const w of d.writes()){const a=tables[w.table_name],i=a.findIndex(x=>x._row===w.row_no);if(i<0)a.push(w.data);else a[i]=w.data;}for(const c of d.cacheWrites())if(c.remove)delete cache[c.key];else cache[c.key]=c.value;return r;}
const tasks=e=>call(e,'overview').tasks,find=(e,id)=>tasks(e).find(t=>t.criterionId===id&&!t.cancelled);const submit=(e,t)=>call(e,'submit',{id:t.id,version:t.version,completed:true,completedAt:'2026-10-01',progress:100,quality:100,note:'Đã thực hiện'});
assert.equal(CURRENT_CATALOG.length,233);call('ht','provisionMandatory');assert.equal(tasks('a').length,28);assert.equal(tasks('leader').length,25);assert.equal(tasks('vpd').length,21);assert.equal(tasks('vt').length,12);assert.equal(call('ht','provisionMandatory').created,0);
assert.throws(()=>call('a','register',{criterionId:'GVBM-1'}),/bắt buộc/);assert.throws(()=>call('vt','profile',{email:'kt'}),/quyền/);assert.throws(()=>submit('a',find('a','GVBM-1')),/thời hạn/);assert.equal(call('hp','setUnitSchedule',{unit:'Ngoại ngữ',criterionId:'TTCM-1',due:'2026-11-01',note:'Lịch'}).changed.length,0);
let r=call('leader','setUnitSchedule',{unit:'Ngoại ngữ',criterionId:'GVBM-1',due:'2026-11-01',note:'Lịch'});assert.equal(r.changed.length,3);assert.equal(r.skipped.length,1);for(const e of ['a','b'])submit(e,find(e,'GVBM-1'));
const extra=call('a','register',{criterionId:'GVBM-13',output:'Giao riêng',due:'2026-11-01',inPlan:false});call('leader','approvePlan',{id:extra.id,version:1,accept:true,coef:1.1,inPlan:false,note:'Giao riêng'});submit('a',find('a','GVBM-13'));
let preview=call('leader','unitBulkPreview',{unit:'Ngoại ngữ',note:'Đối chiếu toàn tổ'});assert.equal(preview.results.length,2);assert.ok(!preview.results.some(r=>r.data.id===extra.id));assert.throws(()=>call('ht','unitBulkCommit',{previewId:preview.previewId}),/người khác/);r=call('leader','unitBulkCommit',{previewId:preview.previewId});assert.equal(r.results.filter(r=>r.ok).length,2);assert.equal(find('a','GVBM-13').reviewStatus,'pending');assert.equal(call('leader','unitBulkCommit',{previewId:preview.previewId}).results.length,2);
const items=Array.from({length:13},(_,i)=>({name:'Nhập điểm '+(i+1),due:i<6?'2026-10-30':'2027-03-30',weight:1}));call('leader','setUnitSchedule',{unit:'Ngoại ngữ',criterionId:'GVBM-4',items,note:'Các đợt nhập điểm'});let t4=find('a','GVBM-4');assert.equal(t4.occurrences.length,13);call('leader','delegateUnit',{unit:'Ngoại ngữ',delegate:'deputy',roles:['GVBM'],from:'2026-09-01',until:'2027-06-01',finalApproval:false,note:'Kiểm tra'});
for(const o of t4.occurrences)call('a','submitOccurrence',{id:o.id,version:o.version,completed:true,completedAt:'2026-10-01',progress:100,quality:100,note:'Đủ điểm'});preview=call('deputy','unitBulkPreview',{unit:'Ngoại ngữ',mode:'check',note:'Kiểm tra'});assert.equal(preview.results.filter(r=>r.ok).length,13);call('deputy','unitBulkCommit',{previewId:preview.previewId});assert.equal(find('a','GVBM-4').occurrences[0].status,'checked');assert.equal(call('deputy','unitBulkPreview',{unit:'Ngoại ngữ',note:'Không được duyệt cuối'}).results.length,0);preview=call('leader','unitBulkPreview',{unit:'Ngoại ngữ',note:'Duyệt'});call('leader','unitBulkCommit',{previewId:preview.previewId});const report=call('leader','reportPage',{quarter:1}),p=report.people.find(p=>p.user.email==='a');assert.equal(p.tasks.find(t=>t.id===t4.id).quarterMax,4.62);assert.equal(p.tasks.find(t=>t.id===t4.id).quarterScore,4.62);assert.equal(p.summary.total,null);assert.equal(report.quarter.from,'2026-09-05');assert.equal(report.quarter.to,'2026-11-06');
call('vpl','delegateUnit',{unit:'Văn phòng',delegate:'vpd',roles:['VT'],from:'2026-09-01',until:'2027-06-01',finalApproval:true,note:'Ủy quyền'});let vt=find('vt','VT-1');call('vpl','setDeadline',{id:vt.id,version:1,due:'2026-10-30',note:'Lịch'});submit('vt',find('vt','VT-1'));preview=call('vpd','unitBulkPreview',{unit:'Văn phòng',note:'Duyệt VT'});assert.equal(preview.results.length,1);call('vpd','unitBulkCommit',{previewId:preview.previewId});assert.equal(find('vt','VT-1').reviewStatus,'approved');assert.throws(()=>call('ht','assignOffice',{email:'a',roles:['KT'],note:'Quyết định'}),/rà soát/);call('ht','assignOffice',{email:'math',roles:['TQUY'],note:'Quyết định'});assert.equal(call('math','overview').user.unit,'Văn phòng');assert.equal(tasks('math').filter(t=>!t.cancelled).length,8);
const gr=call('a','graduateBonus',{taskId:find('a','GVBM-1').id,examYear:2027,category:'Tốt nghiệp cao hơn Thành phố',reference:'Số liệu thi 2027'});assert.equal(gr.targetPeriod,'2027-2028');assert.equal(gr.assessmentYear,2028);call('ht','approveGraduateBonus',{id:gr.id,version:1,accept:true,note:'Quy chế trường'});assert.equal(call('a','overview').summary.reward,0);assert.equal(tables.kpi_thuong.find(r=>r.id===gr.id).period,'2027-2028');assert.throws(()=>call('a','graduateBonus',{taskId:find('a','GVBM-1').id,examYear:2027,category:'Tốt nghiệp bằng Thành phố',reference:'Số liệu thi 2027'}),/trùng/);
// More than one queue page: a server-side batch must include all 50 people, and skip a stale row.
for(let i=0;i<50;i++){const email='batch'+i;tables.gvcnv.push({_row:tables.gvcnv.length+2,Email:email,'Họ và tên':email,'Vai trò KPI':'GVBM',Tổ:'Ngoại ngữ'});const c=CURRENT_CATALOG.find(c=>c.id==='GVBM-3');tables.kpi_cong_viec.push({_row:tables.kpi_cong_viec.length+2,id:crypto.randomUUID(),email,period:'2026-2027',criterionId:c.id,title:c.title,role:c.role,output:c.output,due:'2026-10-30',kind:c.kind,base:c.base,coef:c.coef,inPlan:true,planStatus:'approved',progress:100,quality:100,completed:true,completedAt:'2026-10-01',reviewStatus:'pending',version:1,cancelled:false,note:'Batch fixture'});}
preview=call('leader','unitBulkPreview',{unit:'Ngoại ngữ',role:'GVBM',note:'Kiểm tra lô hơn 40 hồ sơ'});assert.equal(preview.results.length,50);assert.ok(call('leader','workspace').pages>1);const staleId=preview.results[0].data.id;tables.kpi_cong_viec.find(t=>t.id===staleId).version++;r=call('leader','unitBulkCommit',{previewId:preview.previewId});assert.equal(r.results.filter(r=>r.ok).length,49);assert.equal(r.results.filter(r=>!r.ok).length,1);assert.equal(tables.kpi_cong_viec.find(t=>t.id===staleId).reviewStatus,'pending');assert.equal(call('leader','unitBulkCommit',{previewId:preview.previewId}).results.filter(r=>r.ok).length,49);
console.log('PASS mandatory tasks, unit bulk, delegated office review, quarterly weight, graduation carryover');
