import assert from 'node:assert/strict';import vm from 'node:vm';import {createHash} from 'node:crypto';import {mirrorSnapshot,buildMirrorScript} from '../supabase/functions/kpi-api/mirror.js';
const snapshot={revision:4,headers:{gvcnv:['Email','Môn','Mật khẩu hash'],kpi_cong_viec:['id','note','version'],kpi_nhat_ky:['secret']},tables:{gvcnv:[{Email:'a@example.test','Môn':'Tiếng Anh','Họ và tên':'A','Mật khẩu hash':'must-not-export','Salt KPI':'must-not-export'}],kpi_cong_viec:[{id:'1',note:'=HYPERLINK("bad")',version:1}],kpi_nhat_ky:[{secret:'must-not-export'}]}};
const projected=mirrorSnapshot(snapshot,'sheet-test');assert.equal(projected.tables.gvcnv.rows[0]['Chuyên môn'],'Tiếng Anh');assert.ok(!JSON.stringify(projected).includes('must-not-export'));assert.ok(!projected.tables.kpi_nhat_ky);
// Exercise the generated Apps Script: existing password cells stay intact, text cannot become a formula.
function sheet(data){return {data,getDataRange(){return {getValues:()=>this.data.map(r=>r.slice())};},getRange(row,col,height=1,width=1){return {setValue:v=>{this.data[row-1]||=[];this.data[row-1][col-1]=v;},setValues:values=>values.forEach((r,i)=>r.forEach((v,j)=>{this.data[row+i-1]||=[];this.data[row+i-1][col+j-1]=v;})),clearContent:()=>{}};},getLastRow(){return this.data.length;},getMaxRows(){return 1000;},getMaxColumns(){return 28;},setFrozenRows(){}};}
const roster=sheet([['Email','Môn','Mật khẩu'],['a@example.test','Old','keep-legacy']]),tasks=sheet([['id','note','version']]);const props={},calls=[];const book={getSheetByName:n=>n==='gvcnv'?roster:tasks,insertSheet:()=>{throw Error('unexpected');}};
const ctx={PropertiesService:{getScriptProperties:()=>({setProperties:o=>Object.assign(props,o),getProperty:k=>props[k],setProperty:(k,v)=>props[k]=v})},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){}})},SpreadsheetApp:{openById:id=>{assert.equal(id,'sheet-test');return book;},flush(){}},ScriptApp:{getProjectTriggers:()=>[],newTrigger:()=>({timeBased:()=>({everyMinutes:()=>({create(){}})})})},UrlFetchApp:{fetch:(url,o)=>{const p=JSON.parse(o.payload);calls.push(p);return {getResponseCode:()=>200,getContentText:()=>JSON.stringify({ok:true,data:p.action==='mirrorSnapshot'?projected:{ok:true}})};}}};
vm.createContext(ctx);vm.runInContext(buildMirrorScript({endpoint:'https://test.invalid',publicKey:'public',token:'read-only-token',spreadsheetId:'sheet-test'}),ctx);ctx.setupKpiMirror();assert.equal(roster.data[1][2],'keep-legacy');assert.equal(roster.data[0][1],'Chuyên môn');assert.equal(roster.data[1][1],'Tiếng Anh');assert.equal(tasks.data[1][1][0],"'");assert.equal(props.KPI_MIRROR_REVISION,'4');assert.ok(calls.some(c=>c.action==='mirrorAck'));
// A missing account blocks roster writes instead of matching people by approximate name.
const before=JSON.stringify(roster.data);projected.tables.gvcnv.rows.push({Email:'missing@example.test'});assert.throws(()=>ctx.syncKpiFromSupabase(),/Tài khoản chưa có/);assert.equal(JSON.stringify(roster.data),before);
globalThis.Deno={env:{get:n=>n==='SUPABASE_URL'?'https://test.invalid':n==='SUPABASE_SECRET_KEYS'?'{"default":"sb_secret_test"}':undefined},serve(){}};const {handle}=await import('../supabase/functions/kpi-api/index.ts');
const mirrorToken='a'.repeat(72),settings={hash:createHash('sha256').update(mirrorToken).digest('hex'),expiresAt:'2099-01-01',spreadsheetId:'sheet-test'};let currentActor='teacher@example.test';let usedSnapshot=false;
globalThis.fetch=async(url,init)=>{const path=String(url).split('/rest/v1/')[1];let data;
 if(path?.startsWith('kpi_runtime_settings?key=eq.sheet_mirror_key'))data=[{value:JSON.stringify(settings)}];else if(path?.startsWith('kpi_state?'))data=[{revision:4,source_id:'sheet-test'}];else if(path==='rpc/kpi_rate_hit')data=true;else if(path==='rpc/kpi_snapshot'){usedSnapshot=true;data=snapshot;}else if(path==='rpc/kpi_authenticated_snapshot')data={credential:{email:currentActor,is_admin:false},tables:{gvcnv:[{Email:currentActor,'Họ và tên':'Test','Vai trò KPI':currentActor.startsWith('ht')?'HT':'GVBM'}]},headers:{gvcnv:['Email','Họ và tên','Vai trò KPI']}};else if(path?.startsWith('kpi_runtime_settings?key=eq.sheet_mirror_status'))data=[];else throw Error(path);return Response.json(data);};
async function call(action,key='',payload={}){return (await handle(new Request('https://test.invalid',{method:'POST',headers:{'content-type':'application/json','x-kpi-mirror-key':key,'x-kpi-token':'b'.repeat(72)},body:JSON.stringify({action,payload})}))).json();}
assert.equal((await call('mirrorSnapshot')).ok,false);assert.equal(usedSnapshot,false);assert.equal((await call('mirrorSnapshot',mirrorToken,{revision:4})).data.unchanged,true);assert.equal(usedSnapshot,false);assert.equal((await call('mirrorSnapshot',mirrorToken)).data.tables.gvcnv.rows.length,1);assert.equal((await call('sheetMirrorStatus')).ok,false);currentActor='ht@example.test';assert.equal((await call('sheetMirrorStatus')).ok,true);settings.expiresAt='2000-01-01';assert.equal((await call('mirrorSnapshot',mirrorToken)).ok,false);
console.log('PASS mirror authorization, expiry, unchanged revisions, private-field exclusion, password preservation, missing-account guard and formula escaping');
