import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {createDomain} from '../supabase/functions/kpi-api/domain.js';
const snapshot=process.env.KPI_SOURCE_SNAPSHOT;if(!snapshot)throw Error('Cần đặt KPI_SOURCE_SNAPSHOT tới bản đối chiếu riêng tư; không đưa dữ liệu nhân sự vào git.');const data=JSON.parse(fs.readFileSync(snapshot,'utf8'));const source=fs.readFileSync(new URL('../Code.gs',import.meta.url),'utf8');
const ctx=vm.createContext({console,Date,JSON,Math,Number,String,Object,Array,Set,Map,Error,isNaN,Utilities:{formatDate:d=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}});
vm.runInContext(source,ctx);ctx.tables=data.tables;vm.runInContext("function kpiRawRows_(n){return (tables[n]||[]).map(r=>({...r}));}",ctx);
const imported=createDomain(structuredClone(data));const people=imported.people();assert.equal(people.length,92);assert.equal(imported.publicData().catalog.length,59);
for(const person of people){ctx.email=person.email;const before=JSON.parse(JSON.stringify(vm.runInContext("KPI_READ_CACHE={};KPI_INDEX_CACHE={};KPI_PEOPLE_CACHE=null;kpiSummary_(kpiPeople_().find(u=>u.email===email),'2026-2027')",ctx)));const after=createDomain({...structuredClone(data),actor:person.email,sessionToken:'test'}).dispatch('overview',{},'test').summary;assert.deepEqual(after,before,person.name);}
const leader=people.find(p=>p.roles.includes('TTCM')&&p.unit==='Ngoại ngữ'),deputy=people.find(p=>p.roles.includes('TPCM')&&p.roles.includes('GVCN')&&p.unit==='Ngoại ngữ'),math=people.find(p=>p.roles.includes('GVBM')&&p.unit==='Toán'&&!p.roles.includes('TTCM'));
assert.ok(leader);assert.ok(deputy.roles.includes('GVCN'));const domain=createDomain({...structuredClone(data),actor:leader.email,sessionToken:'test'});assert.equal(domain.dispatch('profile',{email:deputy.email},'test').user.email,deputy.email);assert.throws(()=>domain.dispatch('profile',{email:math.email},'test'),/quyền/);
const task=createDomain({...structuredClone(data),actor:deputy.email,sessionToken:'test'});const reg=task.dispatch('register',{criterionId:'GVBM-1',due:'2027-05-30',output:'Kiểm thử riêng',inPlan:true,requestId:crypto.randomUUID()},'test');assert.equal(reg.email,deputy.email);assert.ok(task.writes().some(w=>w.table_name==='kpi_cong_viec'));assert.throws(()=>task.dispatch('approvePlan',{id:reg.id,version:1,accept:true,coef:1,inPlan:true,note:'Không tự duyệt',requestId:crypto.randomUUID()},'test'),/quyền|tự duyệt/);
// Factory instances isolate request data and cache; no state leaks between users.
assert.equal(createDomain({...structuredClone(data),actor:math.email,sessionToken:'other'}).dispatch('overview',{},'other').tasks.length,0);
console.log('92 source summaries match Apps Script exactly; unit scope, roles, no self-review and request isolation passed.');
