const fs=require('node:fs'),assert=require('node:assert/strict'),vm=require('node:vm'),crypto=require('node:crypto');
const {JSDOM,VirtualConsole}=require('jsdom');
const html=fs.readFileSync(__dirname+'/../index.html','utf8');
const staticHtml=html.replace(/<script(?:\s[^>]*)?>[\s\S]*?<\/script>/g,'');
const ids=[...staticHtml.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size,'No duplicate static IDs');
const catalog=JSON.parse(html.match(/<script id="catalogData" type="application\/json">([\s\S]*?)<\/script>/)[1]);assert.equal(catalog.length,59);
for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))if(!m[0].includes('application/json'))new vm.Script(m[1]);
assert.ok(!html.includes('kpi_apps_script_url'));assert.ok(!ids.includes('openConnection'));assert.ok(!html.includes('luonghoa.html'));
const errors=[],virtualConsole=new VirtualConsole();virtualConsole.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM(html,{url:'https://huycomf2020.github.io/luong_hoa_kpi/',runScripts:'dangerously',virtualConsole,beforeParse(w){
 w.crypto.randomUUID=crypto.randomUUID;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
 w.fetch=async()=>({json:async()=>({ok:true,data:{version:'3.0.0-supabase',config:{period:'2026-2027',schoolRule:'Draft',bonusMode:'source'},catalog}})});
}});
const w=dom.window;
(async()=>{
 await new Promise(r=>setTimeout(r,30));assert.equal(errors.length,0,errors.join('\n'));
 assert.match(w.document.getElementById('connectionLabel').textContent,/Đã kết nối/);
 const fixture={user:{email:'teacher@example.test',name:'Giáo viên mẫu',unit:'Tiếng Anh',roles:['GVBM','GVCN','HOANHAP']},tasks:[{id:'p1',email:'teacher@example.test',criterionId:'GVBM-1',title:'Nộp giáo án định kỳ',role:'GVBM',output:'Giáo án',period:'2026-2027',base:10,coef:1,version:2,progress:100,quality:100,inPlan:true,planStatus:'approved',reviewStatus:'partial',due:'2027-05-30',completed:false,occurrences:[{id:'o1',name:'Tháng 10',due:'2026-10-30',weight:1,status:'draft',progress:0,quality:0,version:1},{id:'o2',name:'Tháng 11',due:'2026-11-30',weight:1,status:'approved',progress:100,quality:100,completed:true,completedAt:'2026-10-01',version:2}]}],summary:{A:10,B:5,kpi:35,general:null,reward:0,total:null,count:1,done:0,pending:1,exceedRate:0,dueKpi:null,missing:0,future:2,planConfirmed:false,provisional:true},general:[],bonuses:[],ranking:[],people:[]};
 fixture.tasks[0].person=fixture.user;fixture.tasks[0].rights={check:false,final:false};fixture.workflow={tasks:fixture.tasks,people:[fixture.user],plans:[],delegations:[],appeals:[],lock:{status:'open',version:0}};
 w.fixture=fixture;w.eval('Object.assign(state,fixture);renderAll();');
 assert.ok(w.document.querySelector('[data-wf-submit="o1"]'));assert.equal(w.document.querySelector('[data-wf-review]'),null);assert.equal(w.document.querySelector('#bonusForm button').disabled,true);
 w.eval("selectCriterion('GVBM-1')");assert.match(w.document.querySelector('#criterionDetail').textContent,/Mở các đợt/);assert.equal(w.document.querySelector('#resultForm'),null);
 w.document.querySelector('[data-wf-submit="o1"]').click();assert.equal(w.document.querySelector('#wfDialog').open,true);assert.equal(w.document.querySelector('#wfFile').required,false);assert.match(w.document.querySelector('#wfContent').textContent,/VnEdu/);w.document.querySelector('#wfClose').click();
 w.eval("state.user={email:'deputy@example.test',name:'TPCM mẫu',unit:'Tiếng Anh',roles:['GVBM','TPCM']};state.workflow.tasks[0].rights={check:true,final:false};state.workflow.tasks[0].occurrences[0].status='pending';renderAll();");
 assert.match(w.document.querySelector('[data-wf-review="o1"]').textContent,/Kiểm tra/);w.document.querySelector('[data-wf-review="o1"]').click();assert.equal(w.document.querySelector('#wfProgress'),null);w.document.querySelector('#wfClose').click();
 w.eval("state.user={email:'leader@example.test',name:'TTCM mẫu',unit:'Tiếng Anh',roles:['GVBM','TTCM']};state.workflow.tasks[0].rights={check:true,final:true};renderAll();");
 assert.ok(w.document.querySelector('#wfDelegate'));assert.ok(w.document.querySelector('#wfPlan'));assert.equal(w.document.querySelector('#wfLock'),null);
 w.document.querySelector('[data-wf-review="o1"]').click();assert.ok(w.document.querySelector('#wfProgress'));w.document.querySelector('#wfClose').click();
 w.eval("state.user={email:'principal@example.test',name:'Hiệu trưởng mẫu',unit:'BGH',roles:['HT']};renderAll();");assert.ok(w.document.querySelector('#wfLock'));
 w.eval("openPage('about')");assert.equal(w.document.querySelector('#about').classList.contains('active'),true);assert.equal(w.document.querySelectorAll('#about details').length,5);assert.equal(w.document.querySelectorAll('.guide-flow div').length,3);
 let report='';w.reportWin={document:{write(v){report=v;},close(){}}};w.reportFixture={period:'2026-2027',generatedAt:new Date().toISOString(),rule:'Draft',people:[{user:fixture.user,summary:fixture.summary,tasks:fixture.tasks,general:[],bonuses:[]}]};w.eval('exportPdf(reportFixture,reportWin)');assert.match(report,/Tháng 10/);assert.match(report,/Trọng số/);assert.match(report,/Kết quả tạm tính/);
 w.eval(fs.readFileSync(require.resolve('exceljs/dist/exceljs.min.js'),'utf8'));let downloadResolve;const download=new Promise(r=>downloadResolve=r);w.downloadBlob=(blob,name)=>{const reader=new w.FileReader();reader.onload=()=>downloadResolve({name,bytes:Buffer.from(reader.result)});reader.readAsArrayBuffer(blob);};await w.eval('exportExcel(reportFixture)');const exported=await download;assert.match(exported.name,/\.xlsx$/);const workbook=new (require('exceljs').Workbook)();await workbook.xlsx.load(exported.bytes);assert.ok(workbook.getWorksheet('Các đợt thực hiện'));assert.equal(workbook.getWorksheet('Các đợt thực hiện').getCell('D8').value,'Tháng 10');assert.equal(workbook.getWorksheet('Nhiệm vụ').getCell('L8').value,5);assert.ok(workbook.getWorksheet('Đối chiếu & dữ liệu'));
 w.reportPages=[{period:'2026-2027',revision:'11',page:1,pages:2,people:[{id:1}]},{period:'2026-2027',revision:'11',page:2,pages:2,people:[{id:2}]}];w.eval("state.version='2.0.0';api=async()=>reportPages.shift()");assert.equal((await w.eval('loadReport()')).people.length,2);w.reportPages=[{period:'2026-2027',revision:'11',page:1,pages:2,people:[]},{period:'2026-2027',revision:'12',page:2,pages:2,people:[]}];await assert.rejects(w.eval('loadReport()'),/Dữ liệu thay đổi/);
 let calls=[];w.fetch=async(url,options)=>{calls.push({url,options});return {json:async()=>({ok:true,data:{value:42}})};};w.eval("state.token='test-token'");assert.equal((await w.eval("request('overview')")).value,42);assert.equal(calls.length,1);assert.ok(calls[0].url.includes('supabase.co/functions/v1'));assert.equal(calls[0].options.headers['x-kpi-token'],'test-token');assert.equal(JSON.parse(calls[0].options.body).action,'overview');w.fetch=async()=>({json:async()=>({ok:false,error:'Không có quyền'})});await assert.rejects(w.eval("request('profile')"),/Không có quyền/);assert.ok(!html.includes('kpiPoll'));assert.ok(!html.includes('script.google.com'));assert.ok(html.includes('icons/favicon.svg'));assert.equal(w.eval("evidenceLink({fileId:'sb:test/file.pdf',fileName:'Minh chứng'})").includes('data-evidence'),true);

 assert.equal(errors.length,0,errors.join('\n'));dom.window.close();console.log('UI DOM tests passed: bootstrap, role controls, recurring forms, guide, optional evidence, reward gate, PDF detail and real XLSX workbook.');
})().catch(e=>{console.error(e);dom.window.close();process.exit(1);});
