/* Detailed reports use server-authorized data only. */
function reportHeader(){return ['TRƯỜNG THPT LỘC NINH','CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM','Độc lập – Tự do – Hạnh phúc'];}
function reportDate(r){return new Intl.DateTimeFormat('vi-VN',{timeZone:'Asia/Ho_Chi_Minh',day:'numeric',month:'numeric',year:'numeric'}).format(new Date(r.generatedAt));}
async function loadExcelJS(){if(window.ExcelJS)return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/exceljs@4.4.0/dist/exceljs.min.js';s.onload=resolve;s.onerror=()=>reject(Error('Không tải được thư viện Excel. Kiểm tra kết nối và thử lại.'));document.head.append(s);});}
function downloadBlob(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function exportExcel(r){
 await loadExcelJS();const w=new ExcelJS.Workbook();w.creator='THPT Lộc Ninh';w.created=new Date(r.generatedAt);
 function sheet(name,columns,headers){const s=w.addWorksheet(name,{pageSetup:{paperSize:9,orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0,margins:{left:1.18,right:.79,top:.79,bottom:.79,header:.3,footer:.3},printTitlesRow:'1:7'},headerFooter:{differentFirst:true,oddHeader:'&C&P',firstHeader:''}});s.columns=columns.map((width,i)=>({key:'c'+i,width}));s.mergeCells(1,1,1,Math.min(3,columns.length));s.getCell('A1').value=reportHeader()[0];s.mergeCells(1,4,1,columns.length);s.getCell('D1').value=reportHeader()[1];s.mergeCells(2,4,2,columns.length);s.getCell('D2').value=reportHeader()[2];s.mergeCells(4,1,4,columns.length);s.getCell('A4').value='BÁO CÁO CHI TIẾT KẾT QUẢ KPI NĂM HỌC '+r.period;s.mergeCells(5,1,5,columns.length);s.getCell('A5').value='Lộc Ninh, ngày '+reportDate(r)+' — '+name;s.mergeCells(6,1,6,columns.length);s.getCell('A6').value=r.rule;s.addRow(headers);s.views=[{state:'frozen',ySplit:7}];return s;}
 const sum=sheet('Tổng hợp',[6,27,18,12,12,12,12,12,12,17,15,22,28,30],['STT','Họ và tên','Tổ','A','B','KPI /70','Chung /30','Thưởng','Tổng /100','Hoàn thành','Vượt (%)','Đề xuất XS','Xếp loại theo quyết định','Số quyết định']);
 r.people.forEach((p,i)=>{const s=p.summary;sum.addRow([i+1,p.user.name,p.user.unit,s.A,s.B,s.kpi,s.general,s.reward,s.total,s.done+'/'+s.count,s.exceedRate,s.excellentEligible?'Đủ điều kiện xem xét':'Chờ xem xét',s.rating||'Chờ hội đồng',s.decisionReference||'']);});
 const detail=sheet('Nhiệm vụ',[25,17,48,30,13,13,10,10,12,12,12,15,20,40],['Họ và tên','Tổ','Nhiệm vụ','Sản phẩm','Hạn','Hoàn thành','Chuẩn','Hệ số','Tối đa','Tiến độ %','Chất lượng %','Quy đổi','Trạng thái','Kết quả / Minh chứng']);
 r.people.forEach(p=>p.tasks.forEach(t=>{const row=detail.addRow([p.user.name,p.user.unit,t.title,t.output,t.due,t.completedAt||'',t.base,t.coef,null,t.progress,t.quality,null,t.planStatus+'/'+t.reviewStatus+(t.cancelled?' / Hủy':''),t.note+(t.fileName?'\nMinh chứng: '+t.fileName:'')]);const n=row.number;row.getCell(9).value={formula:`G${n}*H${n}`,result:KpiCore.round(t.base*t.coef)};row.getCell(12).value={formula:`ROUND(G${n}*H${n}*(0.3*J${n}/100+0.7*K${n}/100),2)`,result:KpiCore.score(t).actual};if(t.fileId)row.getCell(14).value={text:t.note+'\n'+t.fileName,hyperlink:'https://drive.google.com/file/d/'+t.fileId+'/view'};}));
 const common=sheet('Tiêu chí chung',[25,18,28,28,28,28,28,28,18,50],['Họ và tên','Tổ',...generalLabels,'Trạng thái','Nhận xét']);r.people.forEach(p=>p.general.forEach(g=>common.addRow([p.user.name,p.user.unit,...JSON.parse(g.scores),g.status,g.note])));
 const bonus=sheet('Điểm thưởng',[25,18,28,36,12,12,18,25,50],['Họ và tên','Tổ','Thành tích','Nhiệm vụ liên quan','Đề xuất','Được duyệt','Trạng thái','Người duyệt','Căn cứ']);r.people.forEach(p=>p.bonuses.forEach(b=>bonus.addRow([p.user.name,p.user.unit,b.category,b.taskId,Number(b.requested),Number(b.approved),b.status,b.reviewer||'',b.reference])));
 for(const s of w.worksheets){s.eachRow((row,n)=>{row.font={name:'Times New Roman',size:13};row.alignment={vertical:'middle',wrapText:true};row.height=n===6?46:n<=7?28:Math.max(30,Math.min(180,Math.ceil(Math.max(...row.values.filter(x=>typeof x==='string').map(x=>x.length),1)/45)*18));if(n===1||n===2||n===4||n===7)row.font={name:'Times New Roman',size:13,bold:true};if(n===7){row.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFE4EEE9'}};}if(n>=7)row.eachCell({includeEmpty:true},c=>{c.border={top:{style:'thin'},bottom:{style:'thin'},left:{style:'thin'},right:{style:'thin'}};if(typeof c.value==='number')c.numFmt='0.00';});});s.addRow([]);s.addRow(['Người lập báo cáo','','','','Người kiểm tra','','','','HIỆU TRƯỞNG']);s.addRow(['(Ký, ghi rõ họ tên)','','','','(Ký, ghi rõ họ tên)','','','','(Ký, ghi rõ họ tên)']);}
 const bytes=await w.xlsx.writeBuffer();downloadBlob(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),'KPI_Loc_Ninh_'+r.period+'.xlsx');toast('Đã xuất Excel chi tiết theo phạm vi được phân quyền.');
}
function exportPdf(r,existingWindow){
 const win=existingWindow||window.open('','_blank');if(!win)throw Error('Cho phép cửa sổ mới để mở báo cáo PDF.');
 const h=reportHeader();const header=`<div class="letterhead"><div><b>${h[0]}</b></div><div><b>${h[1]}</b><br><b><u>${h[2]}</u></b></div></div><p class="date">Lộc Ninh, ngày ${reportDate(r)}</p><h2>BÁO CÁO CHI TIẾT KẾT QUẢ KPI</h2><p class="center">Năm học ${esc(r.period)}</p><p>${esc(r.rule)}</p>`;
 const table=(headers,rows)=>`<table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
 const total=table(['STT','Họ và tên / Tổ','KPI /70','Chung /30','Thưởng','Tổng /100','Hoàn thành / Vượt','Đề xuất XS'],r.people.map((p,i)=>[i+1,p.user.name+' / '+p.user.unit,fmt(p.summary.kpi),fmt(p.summary.general),fmt(p.summary.reward),fmt(p.summary.total),p.summary.done+'/'+p.summary.count+' / '+p.summary.exceedRate+'%',(p.summary.rating||'Chờ hội đồng')+'; '+(p.summary.decisionReference||'')+'; '+(p.summary.excellentEligible?'Đủ điều kiện đề xuất XS':'Chờ xem xét')]));
 const details=r.people.map(p=>`<section class="person"><h3>${esc(p.user.name)} — ${esc(p.user.unit)}</h3><p>A = ${fmt(p.summary.A)}; B = ${fmt(p.summary.B)}; KPI = ${fmt(p.summary.kpi)}; tổng = ${fmt(p.summary.total)}.</p>${p.tasks.map(t=>`<div class="task"><b>${esc(t.title)}</b><p>Sản phẩm: ${esc(t.output)}. Hạn: ${esc(t.due)}. Hoàn thành: ${esc(t.completedAt||'Chưa kê khai')}. Chuẩn ${t.base}; hệ số ${t.coef}; tối đa ${fmt(t.base*t.coef)}. Tiến độ ${t.progress}%; chất lượng ${t.quality}%; quy đổi ${fmt(KpiCore.score(t).actual)}. ${t.inPlan?'Thuộc kế hoạch A':'Phát sinh ngoài A'}. Trạng thái ${esc(t.planStatus)} / ${esc(t.reviewStatus)}${t.cancelled?' / Hủy':''}.</p><p>Kết quả: ${esc(t.note||'Chưa có')}. Minh chứng: ${esc(t.fileName||'Không đính kèm')}.</p></div>`).join('')}${p.general.map(g=>`<h4>Tiêu chí chung — ${esc(g.status)}</h4>${table(['Tiêu chí','Điểm /5'],generalLabels.map((l,i)=>[l,JSON.parse(g.scores)[i]]))}<p>${esc(g.note)}</p>`).join('')}<h4>Điểm thưởng</h4>${table(['Thành tích','Đề xuất','Được duyệt','Trạng thái / Căn cứ'],p.bonuses.map(b=>[b.category,fmt(b.requested),fmt(b.approved),b.status+' / '+b.reference]))}</section>`).join('');
 win.document.write(`<!doctype html><html lang="vi"><meta charset="utf-8"><title>KPI Lộc Ninh ${esc(r.period)}</title><style>@page{size:A4;margin:20mm 20mm 20mm 30mm}body{font:13pt 'Times New Roman',serif;color:#000;line-height:1.2}p{margin:6pt 0;text-align:justify}h2,h3,h4{margin:12pt 0 6pt}h2{font-size:14pt;text-align:center}.letterhead{display:grid;grid-template-columns:40% 60%;text-align:center;font-size:12pt}.date{text-align:right;font-style:italic}.center{text-align:center}table{width:100%;border-collapse:collapse;font-size:13pt}th,td{border:1px solid #000;padding:5pt;vertical-align:top;overflow-wrap:anywhere}thead{display:table-header-group}tr{break-inside:avoid}.person{break-before:page}.task{border-bottom:1px solid #aaa;padding:6pt 0}.signatures{display:flex;justify-content:space-between;margin-top:18pt;text-align:center}.toolbar{background:#eee;padding:12px;font:16px Arial;position:sticky;top:0}@media print{.toolbar{display:none}}</style><div class="toolbar"><button onclick="window.print()">In / Lưu thành PDF</button> Chọn A4, tỷ lệ 100%, bật số trang ở đầu trang nếu cần. Báo cáo có dữ liệu nhân sự trong phạm vi tài khoản.</div>${header}${total}${details}<div class="signatures"><div>NGƯỜI LẬP BÁO CÁO<br><i>(Ký, ghi rõ họ tên)</i></div><div>NGƯỜI KIỂM TRA<br><i>(Ký, ghi rõ họ tên)</i></div><div><b>HIỆU TRƯỞNG</b><br><i>(Ký, ghi rõ họ tên)</i></div></div></html>`);win.document.close();toast('Báo cáo đã mở. Chọn In / Lưu thành PDF.');
}
