/* Browser-only simulation. No API, account or file operation leaves this sandbox. */
const DemoKernel=(()=>{
const KEY='locninh-kpi-role-demo-v32';
const ACTORS=[
{id:'teacher',email:'teacher@example.test',label:'Giáo viên · GVBM / GVCN / Hòa nhập',name:'Giáo viên mẫu A',roles:'GVBM GVCN HOANHAP',unit:'Ngoại ngữ'},
{id:'deputy',email:'deputy@example.test',label:'Tổ phó chuyên môn (TPCM)',name:'Tổ phó mẫu',roles:'GVBM TPCM',unit:'Ngoại ngữ'},
{id:'leader',email:'leader@example.test',label:'Tổ trưởng chuyên môn (TTCM)',name:'Tổ trưởng mẫu',roles:'GVBM TTCM',unit:'Ngoại ngữ'},
{id:'vice',email:'vice@example.test',label:'Phó Hiệu trưởng',name:'Phó Hiệu trưởng mẫu',roles:'PHT',unit:'BGH'},
{id:'principal',email:'principal@example.test',label:'Hiệu trưởng',name:'Hiệu trưởng mẫu',roles:'HT',unit:'BGH'},
{id:'admin',email:'admin@example.test',label:'Quản trị viên tài khoản',name:'Quản trị viên mẫu',roles:'GVBM',unit:'Văn phòng'},
{id:'officeLeader',email:'office-leader@example.test',label:'Tổ trưởng văn phòng / Văn thư',name:'Tổ trưởng văn phòng mẫu',roles:'TTVP VT',unit:'Văn phòng'},
{id:'officeDeputy',email:'office-deputy@example.test',label:'Tổ phó văn phòng / Kế toán',name:'Tổ phó văn phòng mẫu',roles:'TPVP KT',unit:'Văn phòng'},
{id:'clerk',email:'clerk@example.test',label:'Văn thư',name:'Văn thư mẫu',roles:'VT',unit:'Văn phòng'},
{id:'accountant',email:'accountant@example.test',label:'Kế toán',name:'Kế toán mẫu',roles:'KT',unit:'Văn phòng'},
{id:'outsider',email:'math@example.test',label:'Giáo viên tổ khác · kiểm tra phạm vi',name:'Giáo viên mẫu B',roles:'GVBM',unit:'Toán'}];
let data,catalog=[],sessions=new Map(),evidenceUrls=new Map();
const clone=x=>structuredClone(x),sha=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,'0')).join('');
function clock(day){return class extends Date{constructor(...args){super(...(args.length?args:[day+'T01:00:00Z']));}static now(){return Date.parse(day+'T01:00:00Z');}};}
function persist(next){try{localStorage.setItem(KEY,JSON.stringify(next));}catch{throw Error('Bộ nhớ demo đã đầy. Tệp minh chứng demo tối đa 1 MB; xóa/làm lại dữ liệu nếu cần.');}data=next;}
function domain(next,email,token='demo-seed'){return createDomain({tables:next.tables,headers:DEMO_HEADERS,actor:email,sessionToken:token,cacheValues:Object.fromEntries(Object.entries(next.cache).filter(([,v])=>v.until>Date.now()).map(([k,v])=>[k,v.value])),clock:clock(next.day),prepareFile:(f,u,t)=>{if(!f.base64||f.base64.length>1400000)throw Error('Demo chỉ nhận minh chứng tối đa 1 MB.');if(!['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','image/png','image/jpeg','image/webp'].includes(f.mimeType))throw Error('Định dạng minh chứng không được hỗ trợ.');const id='demo:'+crypto.randomUUID(),ext={ 'application/pdf':'.pdf','image/png':'.png','image/jpeg':'.jpg','image/webp':'.webp','application/msword':'.doc','application/vnd.openxmlformats-officedocument.wordprocessingml.document':'.docx','application/vnd.ms-excel':'.xls','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':'.xlsx'}[f.mimeType];const name=[u.name,u.unit,t.title].join('_').replace(/[\\/:*?"<>|\r\n]/g,'_').slice(0,190)+ext;next.files[id]={base64:f.base64,mime:f.mimeType,name};return {fileId:id,fileName:name};}});}
function dispatch(next,email,action,p={},token='demo-seed'){const engine=domain(next,email,token),r=engine.dispatch(action,p,token);for(const c of engine.cacheWrites()){if(c.remove)delete next.cache[c.key];else next.cache[c.key]={value:c.value,until:Date.now()+c.ttl*1000};}return clone(r);}
function decorate(result){if(!result||typeof result!=='object')return result;if(result.fileId?.startsWith('demo:')){const f=data.files[result.fileId];if(f){if(!evidenceUrls.has(result.fileId)){const bytes=Uint8Array.from(atob(f.base64),c=>c.charCodeAt(0));evidenceUrls.set(result.fileId,URL.createObjectURL(new Blob([bytes],{type:f.mime})));}result.fileUrl=evidenceUrls.get(result.fileId);}}for(const v of Object.values(result))if(v&&typeof v==='object')decorate(v);return result;}
function session(token){const s=sessions.get(token);if(!s||!data.accounts[s.email]||data.accounts[s.email].version!==s.version)throw Error('Phiên demo đã hết hạn hoặc mật khẩu đã đổi. Chọn lại vai trò.');return {email:s.email,account:data.accounts[s.email]};}
function seed(mode){const next={format:1,scenario:mode,day:mode==='yearEnd'?'2027-06-01':'2026-10-07',tables:{},cache:{},accounts:{},files:{},adminAudit:[]};for(const n of Object.keys(DEMO_HEADERS))next.tables[n]=[];
next.tables.gvcnv=ACTORS.map((a,i)=>({_row:i+2,'Họ và tên':a.name,Email:a.email,Tổ:a.unit,Môn:a.unit,'Chức vụ':a.label,'Vai trò KPI':a.roles,'Lớp chủ nhiệm':a.id==='teacher'?'12A mẫu':'','Hòa nhập':a.id==='teacher'?'Có':'','Nhóm nhiệm vụ tương đồng':'DEMO','Phiên bản mật khẩu':1}));next.tables.bang_luong_hoa_kpi=catalog.map((c,i)=>({...c,_row:i+2}));next.tables.kpi_cau_hinh=[{key:'period',value:'2026-2027',_row:2},{key:'schoolRule',value:'DEMO: dữ liệu giả lập; quy chế thử nghiệm, không dùng xếp loại thật.',_row:3},{key:'bonusMode',value:'source',_row:4}];
const e=id=>ACTORS.find(a=>a.id===id).email,T=e('teacher'),L=e('leader'),D=e('deputy'),HT=e('principal'),HP=e('vice');
function make(owner,id,status='draft',reviewer=HT){const c=catalog.find(c=>c.id===id);let t={_row:next.tables.kpi_cong_viec.length+2,id:crypto.randomUUID(),email:owner,period:'2026-2027',criterionId:id,title:c.title,role:c.role,output:'Sản phẩm minh họa '+id,due:mode==='yearEnd'?'2027-05-20':'2026-10-30',kind:c.kind,base:c.base,coef:c.coef,inPlan:true,planStatus:'pending',planAt:next.day,progress:0,quality:0,completed:false,reviewStatus:'draft',version:1,cancelled:false};next.tables.kpi_cong_viec.push(t);if(status==='plan')return t;Object.assign(t,{planStatus:'approved',version:2});if(status==='draft')return t;t=dispatch(next,owner,'submit',{id:t.id,version:t.version,completed:true,completedAt:mode==='yearEnd'?'2027-05-18':'2026-10-01',progress:100,quality:80,note:'Kết quả giả lập: đủ sản phẩm, cần chỉnh sửa nhỏ.'});if(status==='pending')return t;return dispatch(next,reviewer,'review',{id:t.id,version:t.version,accept:true,progress:100,quality:80,note:'Đã duyệt kết quả giả lập'});}
if(mode==='work'){
 dispatch(next,HT,'provisionMandatory');
 const get=(email,id)=>next.tables.kpi_cong_viec.find(t=>t.email===email&&t.criterionId===id&&!t.cancelled);
 dispatch(next,L,'setUnitSchedule',{unit:'Ngoại ngữ',criterionId:'GVBM-1',due:'2026-10-30',note:'Lịch kiểm tra mẫu'});
 let t=get(T,'GVBM-1');dispatch(next,T,'submit',{id:t.id,version:t.version,completed:true,completedAt:'2026-10-01',progress:100,quality:100,note:'Kết quả mẫu chờ duyệt theo tổ'});
 for(const id of ['GVBM-2','GVBM-4']){t=get(T,id);const count=id==='GVBM-2'?8:13;const items=Array.from({length:count},(_,i)=>({name:(id==='GVBM-2'?'Kiểm tra giáo án':'Nhập điểm KTTX/GK/CK')+' đợt '+(i+1),due:i<2?'2026-10-30':i<5?'2027-01-08':'2027-05-20',weight:1}));dispatch(next,L,'setUnitSchedule',{unit:'Ngoại ngữ',criterionId:id,items,note:'Lịch các đợt mẫu'});const os=next.tables.kpi_dot.filter(o=>o.taskId===t.id);for(const o of os.slice(0,2))dispatch(next,T,'submitOccurrence',{id:o.id,version:1,completed:true,completedAt:'2026-10-01',progress:100,quality:100,note:'Đã nộp sản phẩm mẫu'});}
 dispatch(next,L,'delegateUnit',{unit:'Ngoại ngữ',delegate:D,roles:['GVBM'],from:'2026-09-01',until:'2027-06-30',finalApproval:false,note:'TPCM kiểm tra, TTCM duyệt cuối'});
 dispatch(next,HT,'delegateUnit',{unit:'Ngoại ngữ',delegate:HP,roles:['TTCM'],from:'2026-09-01',until:'2027-06-30',finalApproval:true,note:'HP được phân công duyệt TTCM'});
 dispatch(next,HT,'setUnitSchedule',{unit:'Ngoại ngữ',criterionId:'TTCM-1',due:'2026-10-30',note:'Lịch BGH'});t=get(L,'TTCM-1');dispatch(next,L,'submit',{id:t.id,version:t.version,completed:true,completedAt:'2026-10-01',progress:100,quality:100,note:'Báo cáo tổ mẫu'});
 const vl=e('officeLeader'),vd=e('officeDeputy'),v=e('clerk');dispatch(next,vl,'delegateUnit',{unit:'Văn phòng',delegate:vd,roles:['VT'],from:'2026-09-01',until:'2027-06-30',finalApproval:true,note:'Tổ phó văn phòng được giao duyệt văn thư'});dispatch(next,vl,'setUnitSchedule',{unit:'Văn phòng',criterionId:'VT-1',due:'2026-10-30',note:'Lịch văn phòng'});t=get(v,'VT-1');dispatch(next,v,'submit',{id:t.id,version:t.version,completed:true,completedAt:'2026-10-01',progress:100,quality:100,note:'Hồ sơ văn thư mẫu'});
 make(T,'GVBM-13','plan',L);
}else{
 for(const a of ACTORS){const reviewer=a.id==='principal'?HP:HT;let t;if(a.roles.includes('GVBM'))t=make(a.email,'GVBM-1','approved',reviewer);else if(a.roles.includes('VT'))t=make(a.email,'VT-1','approved',reviewer);else if(a.roles.includes('KT'))t=make(a.email,'KT-1','approved',reviewer);else{t=dispatch(next,a.email,'customTask',{title:'Nhiệm vụ quản lý mẫu cuối năm',output:'Báo cáo giả lập',due:'2027-05-20',kind:'Thường xuyên',coef:1,inPlan:true});t=dispatch(next,reviewer,'approvePlan',{id:t.id,version:t.version,accept:true,coef:1,inPlan:true,note:'Kế hoạch demo'});t=dispatch(next,a.email,'submit',{id:t.id,version:t.version,completed:true,completedAt:'2027-05-18',progress:100,quality:100,note:'Báo cáo demo đầy đủ'});t=dispatch(next,reviewer,'review',{id:t.id,version:t.version,accept:true,progress:100,quality:100,note:'Đã duyệt demo'});}
 dispatch(next,reviewer,'general',{email:a.email,scores:[5,5,5,5,5,5],note:'Demo xác nhận điểm chung'});dispatch(next,reviewer,'plan',{email:a.email,requiredIds:[t.criterionId],confirm:true,note:'Đủ phân công demo cuối năm'});dispatch(next,reviewer,'decision',{email:a.email,rating:'Hoàn thành tốt nhiệm vụ',reference:'DEMO-HĐ-01',note:'Quyết định giả lập để thử chốt; không áp dụng thật'});}
}
for(const a of ACTORS)next.accounts[a.email]={isAdmin:a.id==='admin',mustChange:false,version:1,digest:'',temporaryUntil:0};return next;}
async function reset(mode='work'){for(const url of evidenceUrls.values())URL.revokeObjectURL(url);evidenceUrls.clear();sessions.clear();const next=seed(mode);const digest=await sha('DemoKpi2026!');for(const a of Object.values(next.accounts))a.digest=digest;persist(next);}
async function init(c){catalog=clone(c);try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved?.format===1&&saved.tables?.gvcnv?.length===ACTORS.length&&saved.accounts)data=saved;}catch{}if(!data)await reset();}
async function login(email,digest,bypass=false){const a=data.accounts[email];if(!a||(!bypass&&a.digest!==digest))throw Error('Sai tài khoản hoặc mật khẩu demo. Mặc định: DemoKpi2026!');if(a.mustChange&&a.temporaryUntil<Date.now())throw Error('Mật khẩu tạm demo đã hết hạn.');const token=crypto.randomUUID()+crypto.randomUUID();sessions.set(token,{email,version:a.version});const overview=dispatch(clone(data),email,'overview',{},token),account={isAdmin:a.isAdmin,mustChange:a.mustChange};overview.account=account;decorate(overview);return a.mustChange?{token,user:overview.user,account}:{token,user:overview.user,account,overview};}
async function request(action,p={},token=''){
 if(action==='kpiPublic')return domain(clone(data),'').publicData();
 if(action==='login')return login(String(p.email||'').trim().toLowerCase(),p.digest);
 if(action==='recoverAccount')throw Error('Demo không dùng mã Supabase. Bấm Làm lại dữ liệu demo để khôi phục tài khoản mẫu.');
 const {email,account}=session(token);if(action==='logout'){sessions.delete(token);return {ok:true};}
 if(action==='changePassword'){if(p.oldDigest!==account.digest||!/^[a-f0-9]{64}$/.test(p.newDigest)||p.newDigest===p.oldDigest||p.length<10)throw Error('Mật khẩu demo hiện tại sai hoặc mật khẩu mới không hợp lệ.');const next=clone(data);Object.assign(next.accounts[email],{digest:p.newDigest,mustChange:false,temporaryUntil:0,version:account.version+1});persist(next);for(const [k,s]of sessions)if(s.email===email)sessions.delete(k);return {ok:true,relogin:true};}
 if(account.mustChange)throw Error('Cần đổi mật khẩu tạm demo trước khi sử dụng.');
 if(action==='adminAccounts'){if(!account.isAdmin)throw Error('Không có quyền quản trị tài khoản.');return {accounts:ACTORS.map(a=>({email:a.email,name:a.name,unit:a.unit,isAdmin:data.accounts[a.email].isAdmin,mustChange:data.accounts[a.email].mustChange,version:data.accounts[a.email].version})),audit:clone(data.adminAudit).reverse()};}
 if(action==='adminResetPassword'){if(!account.isAdmin||p.email===email)throw Error('Không có quyền đặt lại tài khoản này.');if(!data.accounts[p.email]||data.accounts[p.email].version!==p.version||String(p.reason||'').trim().length<5)throw Error('Tài khoản thay đổi hoặc thiếu lý do.');const temporaryPassword='Demo!'+crypto.randomUUID().replaceAll('-','').slice(0,15),next=clone(data);Object.assign(next.accounts[p.email],{digest:await sha(temporaryPassword),mustChange:true,version:p.version+1,temporaryUntil:Date.now()+86400000});next.adminAudit.push({at:new Date().toISOString(),actor:email,entity:p.email,action:'ADMIN_RESET_PASSWORD',after:JSON.stringify({reason:p.reason,changed:true})});persist(next);for(const [k,s]of sessions)if(s.email===p.email)sessions.delete(k);return {temporaryPassword,expiresHours:24};}
 if(action==='evidenceUrl'){const next=clone(data),engine=domain(next,email,token);const row=[...next.tables.kpi_cong_viec,...next.tables.kpi_dot].find(r=>r.fileId===p.fileId);if(!row)throw Error('Không có minh chứng demo.');if(row.email!==email){try{engine.dispatch('profile',{email:row.email},token);}catch{const w=engine.dispatch('workspace',{focusTaskId:row.taskId||row.id},token);if(!w.tasks.some(t=>t.id===row.id||t.occurrences?.some(o=>o.id===row.id)))throw Error('Không có quyền xem minh chứng demo.');}}return {url:decorate({fileId:p.fileId}).fileUrl};}
 const next=clone(data),result=dispatch(next,email,action,p,token);persist(next);if(action==='overview')result.account={isAdmin:account.isAdmin,mustChange:false};return decorate(result);
}
return {init,reset,request,enter:async id=>{const a=ACTORS.find(a=>a.id===id);if(!a)throw Error('Chọn vai trò demo.');return login(a.email,'',true);},actors:()=>clone(ACTORS),scenario:()=>data.scenario,day:()=>data.day,snapshot:()=>clone(data)};
})();
