/* Browser-only simulation. No API, account or file operation leaves this sandbox. */
const DemoKernel=(()=>{
const KEY='locninh-kpi-role-demo-v1';
const ACTORS=[
{id:'teacher',email:'teacher@example.test',label:'Giáo viên · GVBM / GVCN / Hòa nhập',name:'Giáo viên mẫu A',roles:'GVBM GVCN HOANHAP',unit:'Ngoại ngữ'},
{id:'deputy',email:'deputy@example.test',label:'Tổ phó chuyên môn (TPCM)',name:'Tổ phó mẫu',roles:'GVBM TPCM',unit:'Ngoại ngữ'},
{id:'leader',email:'leader@example.test',label:'Tổ trưởng chuyên môn (TTCM)',name:'Tổ trưởng mẫu',roles:'GVBM TTCM',unit:'Ngoại ngữ'},
{id:'vice',email:'vice@example.test',label:'Phó Hiệu trưởng',name:'Phó Hiệu trưởng mẫu',roles:'PHT',unit:'BGH'},
{id:'principal',email:'principal@example.test',label:'Hiệu trưởng',name:'Hiệu trưởng mẫu',roles:'HT',unit:'BGH'},
{id:'admin',email:'admin@example.test',label:'Quản trị viên tài khoản',name:'Quản trị viên mẫu',roles:'GVBM',unit:'Văn phòng'},
{id:'outsider',email:'math@example.test',label:'Giáo viên tổ khác · kiểm tra phạm vi',name:'Giáo viên mẫu B',roles:'GVBM',unit:'Toán'}];
let data,catalog=[],sessions=new Map(),evidenceUrls=new Map();
const clone=x=>structuredClone(x),sha=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,'0')).join('');
function clock(day){return class extends Date{constructor(...args){super(...(args.length?args:[day+'T01:00:00Z']));}static now(){return Date.parse(day+'T01:00:00Z');}};}
function persist(next){try{localStorage.setItem(KEY,JSON.stringify(next));}catch{throw Error('Bộ nhớ demo đã đầy. Tệp minh chứng demo tối đa 1 MB; xóa/làm lại dữ liệu nếu cần.');}data=next;}
function domain(next,email,token='demo-seed'){return createDomain({tables:next.tables,headers:DEMO_HEADERS,actor:email,sessionToken:token,cacheValues:Object.fromEntries(Object.entries(next.cache).filter(([,v])=>v.until>Date.now()).map(([k,v])=>[k,v.value])),clock:clock(next.day),prepareFile:(f,u,t)=>{if(!f.base64||f.base64.length>1400000)throw Error('Demo chỉ nhận minh chứng tối đa 1 MB.');if(!['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','image/png','image/jpeg','image/webp'].includes(f.mimeType))throw Error('Định dạng minh chứng không được hỗ trợ.');const id='demo:'+crypto.randomUUID(),ext={ 'application/pdf':'.pdf','image/png':'.png','image/jpeg':'.jpg','image/webp':'.webp','application/msword':'.doc','application/vnd.openxmlformats-officedocument.wordprocessingml.document':'.docx','application/vnd.ms-excel':'.xls','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':'.xlsx'}[f.mimeType];const name=[u.name,u.unit,t.title].join('_').replace(/[\\/:*?"<>|\r\n]/g,'_').slice(0,190)+ext;next.files[id]={base64:f.base64,mime:f.mimeType,name};return {fileId:id,fileName:name};}});}
function dispatch(next,email,action,p={},token='demo-seed'){const engine=domain(next,email,token),r=engine.dispatch(action,p,token);for(const c of engine.cacheWrites()){if(c.remove)delete next.cache[c.key];else next.cache[c.key]={value:c.value,until:Date.now()+c.ttl*1000};}return clone(r);}
function decorate(result){if(!result||typeof result!=='object')return result;if(result.fileId?.startsWith('demo:')){const f=data.files[result.fileId];if(f){if(!evidenceUrls.has(result.fileId)){const bytes=Uint8Array.from(atob(f.base64),c=>c.charCodeAt(0));evidenceUrls.set(result.fileId,URL.createObjectURL(new Blob([bytes],{type:f.mime})));}result.fileUrl=evidenceUrls.get(result.fileId);}}for(const v of Object.values(result))if(v&&typeof v==='object')decorate(v);return result;}
function session(token){const s=sessions.get(token);if(!s||!data.accounts[s.email]||data.accounts[s.email].version!==s.version)throw Error('Phiên demo đã hết hạn hoặc mật khẩu đã đổi. Chọn lại vai trò.');return {email:s.email,account:data.accounts[s.email]};}
function seed(mode){const next={format:1,scenario:mode,day:mode==='yearEnd'?'2027-06-01':'2026-10-07',tables:{},cache:{},accounts:{},files:{},adminAudit:[]};for(const n of Object.keys(DEMO_HEADERS))next.tables[n]=[];
next.tables.gvcnv=ACTORS.map((a,i)=>({_row:i+2,'Họ và tên':a.name,Email:a.email,Tổ:a.unit,Môn:a.unit,'Chức vụ':a.label,'Vai trò KPI':a.roles,'Lớp chủ nhiệm':a.id==='teacher'?'12A mẫu':'','Hòa nhập':a.id==='teacher'?'Có':'','Nhóm nhiệm vụ tương đồng':'DEMO','Phiên bản mật khẩu':1}));next.tables.bang_luong_hoa_kpi=catalog.map((c,i)=>({...c,_row:i+2}));next.tables.kpi_cau_hinh=[{key:'period',value:'2026-2027',_row:2},{key:'schoolRule',value:'DEMO: dữ liệu giả lập; quy chế thử nghiệm, không dùng xếp loại thật.',_row:3},{key:'bonusMode',value:'source',_row:4}];
const e=id=>ACTORS.find(a=>a.id===id).email,T=e('teacher'),L=e('leader'),D=e('deputy'),HT=e('principal'),HP=e('vice');
function make(owner,id,status='draft',reviewer=HT){let t=dispatch(next,owner,'register',{criterionId:id,output:'Sản phẩm minh họa cho '+id,due:mode==='yearEnd'?'2027-05-20':'2026-10-30',inPlan:true});if(status==='plan')return t;t=dispatch(next,reviewer,'approvePlan',{id:t.id,version:t.version,accept:true,coef:t.coef,inPlan:true,note:'Phân công demo đã xác nhận'});if(status==='draft')return t;t=dispatch(next,owner,'submit',{id:t.id,version:t.version,completed:true,completedAt:mode==='yearEnd'?'2027-05-18':'2026-10-01',progress:100,quality:80,note:'Kết quả giả lập: đủ sản phẩm, cần chỉnh sửa nhỏ.'});if(status==='pending')return t;return dispatch(next,reviewer,'review',{id:t.id,version:t.version,accept:true,progress:100,quality:80,note:'Đã duyệt kết quả giả lập'});}
if(mode==='work'){
 make(T,'GVBM-1','plan',L);make(T,'HOANHAP-1','plan',L);make(T,'GVBM-4','pending',L);const g=make(T,'GVCN-1','approved',L);
 const t=make(T,'GVBM-2','draft',L);const dates=['2026-10-05','2026-11-05','2026-12-05','2027-01-05','2027-02-05','2027-03-05','2027-04-05','2027-05-05'];const os=dispatch(next,L,'schedule',{taskId:t.id,version:t.version,items:dates.map((due,i)=>({name:'Kiểm tra giáo án đợt '+(i+1),due,weight:1}))});
 dispatch(next,L,'delegate',{delegate:D,teachers:[T],roles:['GVBM'],criterionIds:['GVBM-2'],from:'2026-09-01',until:'2027-06-30',finalApproval:false,note:'Demo: TPCM kiểm tra giáo án, TTCM duyệt cuối'});
 for(let i=0;i<3;i++){let o=dispatch(next,T,'submitOccurrence',{id:os[i].id,version:1,completed:true,completedAt:'2026-10-01',progress:100,quality:i===2?80:100,note:'Minh họa đợt '+(i+1)+': đã nộp đủ giáo án.'});if(i===0)dispatch(next,L,'reviewOccurrence',{id:o.id,version:o.version,accept:true,progress:100,quality:100,note:'Demo: duyệt đợt đầu'});}
 make(D,'TPCM-1','pending',L);make(L,'TTCM-1','pending',HP);make(e('outsider'),'GVBM-1','pending',HT);make(e('admin'),'GVBM-1','draft',HT);
 dispatch(next,T,'general',{scores:[5,5,5,5,4,5],note:'Tự đánh giá mẫu, chờ TTCM xác nhận'});
 dispatch(next,L,'plan',{email:T,requiredIds:['GVBM-1','GVBM-2','GVBM-4','GVCN-1','HOANHAP-1'],confirm:false,note:'Kế hoạch demo còn hai việc chờ giao việc'});
 dispatch(next,T,'bonus',{taskId:g.id,category:'Nổi trội theo PL5',requested:1,reference:'Sản phẩm mẫu, chưa có quyết định thật'});
 dispatch(next,T,'appeal',{taskId:g.id,text:'Demo: đề nghị xem lại mức chất lượng dựa trên kết quả bổ sung.'});
}else{
 for(const a of ACTORS){const reviewer=a.id==='principal'?HP:HT;let t;if(a.roles.includes('GVBM'))t=make(a.email,'GVBM-1','approved',reviewer);else{t=dispatch(next,a.email,'customTask',{title:'Nhiệm vụ quản lý mẫu cuối năm',output:'Báo cáo giả lập',due:'2027-05-20',kind:'Thường xuyên',coef:1,inPlan:true});t=dispatch(next,reviewer,'approvePlan',{id:t.id,version:t.version,accept:true,coef:1,inPlan:true,note:'Kế hoạch demo'});t=dispatch(next,a.email,'submit',{id:t.id,version:t.version,completed:true,completedAt:'2027-05-18',progress:100,quality:100,note:'Báo cáo demo đầy đủ'});t=dispatch(next,reviewer,'review',{id:t.id,version:t.version,accept:true,progress:100,quality:100,note:'Đã duyệt demo'});}
 dispatch(next,reviewer,'general',{email:a.email,scores:[5,5,5,5,5,5],note:'Demo xác nhận điểm chung'});dispatch(next,reviewer,'plan',{email:a.email,requiredIds:[t.criterionId],confirm:true,note:'Đủ phân công demo cuối năm'});dispatch(next,reviewer,'decision',{email:a.email,rating:'Hoàn thành tốt nhiệm vụ',reference:'DEMO-HĐ-01',note:'Quyết định giả lập để thử chốt; không áp dụng thật'});}
}
for(const a of ACTORS)next.accounts[a.email]={isAdmin:a.id==='admin',mustChange:false,version:1,digest:'',temporaryUntil:0};return next;}
async function reset(mode='work'){for(const url of evidenceUrls.values())URL.revokeObjectURL(url);evidenceUrls.clear();sessions.clear();const next=seed(mode);const digest=await sha('DemoKpi2026!');for(const a of Object.values(next.accounts))a.digest=digest;persist(next);}
async function init(c){catalog=clone(c);try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved?.format===1&&saved.tables?.gvcnv?.length===ACTORS.length&&saved.accounts)data=saved;}catch{}if(!data)await reset();}
async function login(email,digest,bypass=false){const a=data.accounts[email];if(!a||(!bypass&&a.digest!==digest))throw Error('Sai tài khoản hoặc mật khẩu demo. Mặc định: DemoKpi2026!');if(a.mustChange&&a.temporaryUntil<Date.now())throw Error('Mật khẩu tạm demo đã hết hạn.');const token=crypto.randomUUID()+crypto.randomUUID();sessions.set(token,{email,version:a.version});const overview=dispatch(clone(data),email,'overview',{},token),account={isAdmin:a.isAdmin,mustChange:a.mustChange};overview.account=account;decorate(overview);return a.mustChange?{token,user:overview.user,account}:{token,user:overview.user,account,overview};}
async function request(action,p={},token=''){
 if(action==='kpiPublic')return domain(clone(data),'').publicData();
 if(action==='login')return login(String(p.email||'').trim().toLowerCase(),p.digest);
 if(action==='recoverAccount')throw Error('Demo không dùng mã Supabase. Bấm Làm lại dữ liệu demo để khôi phục tài khoản mẫu.');
 const {email,account}=session(token);if(action==='logout'){sessions.delete(token);return {ok:true};}
 if(action==='changePassword'){if(p.oldDigest!==account.digest||!/^[a-f0-9]{64}$/.test(p.newDigest)||p.newDigest===p.oldDigest||p.length<10)throw Error('Mật khẩu demo hiện tại sai hoặc mật khẩu mới không hợp lệ.');const next=clone(data);Object.assign(next.accounts[email],{digest:p.newDigest,mustChange:false,temporaryUntil:0,version:account.version+1});persist(next);for(const [k,s]of sessions)if(s.email===email)sessions.delete(k);return {ok:true,relogin:true};}
 if(account.mustChange)throw Error('Cần đổi mật khẩu tạm demo trước khi sử dụng.');
 if(action==='adminAccounts'){if(!account.isAdmin)throw Error('Không có quyền quản trị tài khoản.');return {accounts:ACTORS.map(a=>({email:a.email,name:a.name,unit:a.unit,isAdmin:data.accounts[a.email].isAdmin,mustChange:data.accounts[a.email].mustChange,version:data.accounts[a.email].version})),audit:clone(data.adminAudit).reverse()};}
 if(action==='adminResetPassword'){if(!account.isAdmin||p.email===email)throw Error('Không có quyền đặt lại tài khoản này.');if(!data.accounts[p.email]||data.accounts[p.email].version!==p.version||String(p.reason||'').trim().length<5)throw Error('Tài khoản thay đổi hoặc thiếu lý do.');const temporaryPassword='Demo!'+crypto.randomUUID().replaceAll('-','').slice(0,15),next=clone(data);Object.assign(next.accounts[p.email],{digest:await sha(temporaryPassword),mustChange:true,version:p.version+1,temporaryUntil:Date.now()+86400000});next.adminAudit.push({at:new Date().toISOString(),actor:email,entity:p.email,action:'ADMIN_RESET_PASSWORD',after:JSON.stringify({reason:p.reason,changed:true})});persist(next);for(const [k,s]of sessions)if(s.email===p.email)sessions.delete(k);return {temporaryPassword,expiresHours:24};}
 if(action==='evidenceUrl'){const next=clone(data),engine=domain(next,email,token);const row=[...next.tables.kpi_cong_viec,...next.tables.kpi_dot].find(r=>r.fileId===p.fileId);if(!row)throw Error('Không có minh chứng demo.');if(row.email!==email){try{engine.dispatch('profile',{email:row.email},token);}catch{const w=engine.dispatch('workspace',{focusTaskId:row.taskId||row.id},token);if(!w.tasks.some(t=>t.id===row.id||t.occurrences?.some(o=>o.id===row.id)))throw Error('Không có quyền xem minh chứng demo.');}}return {url:decorate({fileId:p.fileId}).fileUrl};}
 const next=clone(data),result=dispatch(next,email,action,p,token);persist(next);if(action==='overview')result.account={isAdmin:account.isAdmin,mustChange:false};return decorate(result);
}
return {init,reset,request,enter:async id=>{const a=ACTORS.find(a=>a.id===id);if(!a)throw Error('Chọn vai trò demo.');return login(a.email,'',true);},actors:()=>clone(ACTORS),scenario:()=>data.scenario,day:()=>data.day,snapshot:()=>clone(data)};
})();
